name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Init Python
        run: mkdir -p /opt/hostedtoolcache
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Build
        run: make
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
